### ISSUE TITLE
seems to be an issue traversing directories

### ISSUE THREAD

**Issue by imoree** [prateekbhatt/bitfountain-download-all#1]
i get the following error:
Get : unsupported protocol scheme ""
when finished downloading section 1

**Comment by ghost** [comment]
I'm getting two errors;
error #1 (seems to be same with imoree):
(lecture number/title)YYYY/MM/DD HH:MM:SS Get : unsupported protocol scheme ""

error #2:
    lecture number/title.mp4
        wistiaVideoSize: (int value)        Downloading video ...
YYYY/MM/DD HH:MM:SS open (dir to the course file)/(lecture section title)/lecturetitle.mp4: no such file or directory

**Comment by prateekbhatt** [comment]
Looks like sometimes the download urls on bitfountain do not have the url scheme (http / https) explicitly, e.g. just 'embed.wistia.com/abcd' rather than 'http://embed.wistia.com/abcd'. Go panicked if it could not find the http / https in the url. Let me know if the error persists.
