### ISSUE TITLE
Fails downloading half way through lists

### ISSUE THREAD

**Issue by PaulMellor** [prateekbhatt/bitfountain-download-all#3]
Trying to get courses but get either of this  issues/warnings

Resizing Pixel by Pixel  
        wistiaVideoSize: 31195479
        existingFileSizeOnDisk: 31195479
        Full video file exists; moving to next lecture...

```
          Reshaping/Resizing Using the Space Bar

    wistiaVideoSize: 28745834       Downloading video ...
```

2015/05/24 07:36:34 open /Users/paulmellor/bitfountain-download-all-master/ios-design/2-Introduction-to-Sketch/12-Reshaping/Resizing-Using-the-Space-Bar.mp4: no such file or directory

have tried manual adding file but still fails in both errors

**Comment by othyn** [comment]
The first one I do not know the fix to, but the second is down to the script not escaping the "/" character, in which it then thinks that their should be a directory called "12-Reshaping", in which the video is in, with the name "Resizing-Using-the-Space-Bar.mp4".

I'm not familiar with GO, although, I have setup and environment and I am currently messing around with the script. So I'll see what I can do or wait and see if @prateekbhatt can fix it. :)

**Comment by PaulMellor** [comment]
Secondd issue i have managed to Temp fix/bypass by creating the folder that is missing. but first has not reappeared for a while might have been network connect issues.

**Comment by othyn** [comment]
Ah, yes that was my work around.

Although, I have made a fix in the code for this issue, (I'm finding golang quite nice!), so I will probably submit a pull request. :)

**Comment by PaulMellor** [comment]
Any chance posting fix here so i can test and have a look.

**Comment by PaulMellor** [comment]
Separated Issues for Easier fixing and accountability

**Comment by othyn** [comment]
I've submitted a pull request with the fix and a load of new features, take a look and see what you think. :)
